### ISSUE TITLE
nickcolor not using all available colors

### ISSUE THREAD

**Issue by sigmoidbigfoot** [ronilaukkarinen/weed#12]
Hi,

I'm using one of [Chris Kempson's Base16 themes](https://chriskempson.github.io/base16/), using this [Xresources](https://raw.githubusercontent.com/chriskempson/base16-xresources/master/base16-atelierlakeside.dark.xresources).

![colors](https://i.imgur.com/XHCVHmR.png)

`/color preview` output:
![/color preview](https://i.imgur.com/LBRXdlL.png)

As you can see, only the only colors being used by the theme or nicklist.pl (I'm not sure exactly where this takes place) are the bold/bright colors. It should be possible to use the entire range of my colorscheme for nickcolors.

Loving the theme otherwise.

**Comment by ronilaukkarinen** [comment]
Please use [nickcolor_expando](http://anti.teamidiot.de/static/nei/*/Code/Irssi/nickcolor_expando.pl), that's not yet implemented, see [here](https://github.com/ronilaukkarinen/weed/issues/9).
