### ISSUE TITLE
Script Load Fails

### ISSUE THREAD

**Issue by darksheer** [ronilaukkarinen/weed#18]
Trying to load any scripts I receive the following errors -- not sure where to investigate:

/script load trackbar22 irssi: symbol lookup error: irssi: undefined symbol: Perl_Tstack_sp_ptr

**Comment by ailin-nemui** [comment]
your perl is broken, try recompiling irssi and/or recompiling any manually installed perl modules

**Comment by ronilaukkarinen** [comment]
As @ailin-nemui stated, it's not a weed issue but rather a perl issue so closing this.
