### ISSUE TITLE
/away doesn't show in the status bar. Should this happen?

### ISSUE THREAD

**Issue by u8y7541** [ronilaukkarinen/weed#21]
When I type /away it doesn't show in the status bar. Is it supposed to happen?

**Comment by ronilaukkarinen** [comment]
Did you install the awaybar.pl script [as instructed](https://github.com/ronilaukkarinen/weed#away-state-in-status-bar)?

**Comment by u8y7541** [comment]
Oh. Sorry, thanks!

**Comment by ronilaukkarinen** [comment]
No probs!
