### ISSUE TITLE
Statusbar

### ISSUE THREAD

**Issue by Jarvvski** [ronilaukkarinen/weed#22]
How do I get the statusbar to look like the one in your examples?

Mine currently is:

![](https://i.imgur.com/F43Opj7.png)

Also it's showing the topic from a slack chat instead of a channel name. Any ideas?

**Comment by ronilaukkarinen** [comment]
It's all in the documentation. You will need to follow the [Installation](https://github.com/ronilaukkarinen/weed#installation) precisely. You have clearly not resetted your irssi config like instructed, most of the statusbar changes need the customized config, this theme **will not** work out of the box (also stated).

So follow the instructions and load up awl.pl which is included with the repo and add the settings as described.

Here's my `/set awl`

````
 09:42:16  [awl]
 09:42:16  awl_all_disable = OFF
 09:42:16  awl_automode = sbar
 09:42:16  awl_block = 15
 09:42:16  awl_columns = 1
 09:42:16  awl_display_key = %K%0$H $N %N
 09:42:16  awl_display_key_active = %1 $C %N
 09:42:16  awl_display_nokey = %K%0$H $N %N
 09:42:16  awl_display_nokey_active = %1 $C %N
 09:42:16  awl_height_adjust = 1
 09:42:16  awl_hide_data = 0
 09:42:16  awl_maxlines = 9
 09:42:16  awl_placement = bottom
 09:42:16  awl_position = 0
 09:42:16  awl_prefer_name = OFF
 09:42:16  awl_sbar_maxlength = ON
 09:42:16  awl_separator = %N %N
 09:42:16  awl_sort = refnum
 09:42:16  [history]
 09:42:16  rawlog_lines = 200
````

**Comment by Jarvvski** [comment]
My bad @ronilaukkarinen I saw advanced window and just ran my own version of it :)

Thanks.
