### ISSUE TITLE
Display longer usernames

### ISSUE THREAD

**Issue by spacekookie** [ronilaukkarinen/weed#23]
Currently the username that is displayed before the `|` is not long enough for "spacekookie" (which annoys me)

Is there a way to conveniently change that without manually digging through the entire theme and finding out?

Thanks

**Comment by mitral** [comment]
@spacekookie I cant seem to see the trackball script when I load it? any ideas on what I can do to make it appear?

**Comment by ronilaukkarinen** [comment]
Currently changing nick lenght is not a feature, so you have to change it manually. This is already been asked before, see [here](https://github.com/ronilaukkarinen/weed/issues/8) for instance.
