### ISSUE TITLE
Solarized weed - nick colors

### ISSUE THREAD

**Issue by avieks** [ronilaukkarinen/weed#30]
@her, I can't get nick colors to work in chat, NOT nick list. Any ideas? Because non-solarized weed works properly.

**Comment by her** [comment]
hey @avieks that stinks! I'll do some testing to reproduce that on my end and will update. 

Would you mind dropping a screen shot of what it looks like in the meantime?

Thanks 🙏

**Comment by avieks** [comment]
I followed the instructions on the main page so it shouldn't be me.

http://i.imgur.com/IYbbaUl.png

**Comment by her** [comment]
Thanks for the screenshot. 

How have you configured your scripts? 

`nickcolor.pl` is where the "magic" happens with name coloring in weed-Irssi. `~/.irssi/scripts/autorun` is a handy directory to have all your scripts loaded automatically on start (Full description in case other's wander in here). 

You want something like this: 

```sh
~/.irssi/scripts tree autorun/
autorun/
├── awaybar.pl
├── awl.pl
├── nickcolor.pl
├── tmux-nicklist-portable.pl
├── tmux-nicklist.pl
├── trackbar.pl
├── trackbar22.pl
└── usercount.pl
```

If the scripts are loaded correctly you'll get nick coloring:
http://imgur.com/a/9Zhjp

I'm having trouble reproducing this. 

Any other details you can share about your configuration, or how you set this up?

**Comment by avieks** [comment]
Oh, I'm not using nickcolor.pl, I'm using nickcolor_expando.pl, maybe that's the issue. The instructions talks about nickcolor_expando.pl but it's not included so I /script install'd it. I will try whit nickcolor.pl (the one included) later!

**Comment by her** [comment]
Hey that's great news! Thanks for providing an update with your solution 🙏 

Cheers! 🍻
