### ISSUE TITLE
How to enable window titles instead of numbers? 

### ISSUE THREAD

**Issue by mcmillhj-wta** [ronilaukkarinen/weed#31]
Which configuration variable controls what the title of the window are? I was hoping to have the names be present all of the time instead of the window number: 

![screen shot 2017-08-25 at 10 27 58 am](https://user-images.githubusercontent.com/20663938/29718282-347c4116-8980-11e7-987c-57899fbf9be4.png)

I poked through the irssi docs, but didn't see anything obvious that controls this.

**Comment by ronilaukkarinen** [comment]
Hello! it's not in irssi docs, but in awl.pl documentation. Referring to advanced window list, use these settings:

````
/set awl_display_nokey %K%0$H $C %N
/set awl_display_key %K%0$H $C %N
````

**Comment by mcmillhj-wta** [comment]
Awesome, thank you.
