### ISSUE TITLE
/set trackbar_style %r gives error

### ISSUE THREAD

**Issue by SlidingHorn** [ronilaukkarinen/weed#33]
When I set the trackbar_style to red, I get the following error:

`-!- Irssi: Theme weed not found`

I believe something is referencing "weed" rather than "weedsolarized" but I would have no idea where to find that to fix it myself.

**Comment by ronilaukkarinen** [comment]
I don't have any problems with trackbar but I have older irssi version on my machine. This seems to be related to [issue #9, the outdated scripts](https://github.com/ronilaukkarinen/weed/issues/9#issuecomment-133313910) which can cause issues on some platforms/versions.

I no longer use irssi actively (only as irssiproxy) and my time is of the essence so you may have to wait a bit longer for this to be resolved repo-wise. In the meantime you can try [these scripts](https://github.com/ronilaukkarinen/weed/issues/9#issuecomment-133313910) or google ever newer versions.

**Comment by ronilaukkarinen** [comment]
Just to clarify, did you follow the tutorial exactly and is your weed.theme named as weed.theme and not something else?

After more thought that "theme weed not found" error seems not to be from trackbar because it doesn't care which theme you are using...

**Comment by ronilaukkarinen** [comment]
No response for a long time so closing this issue.
