### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by mizlan** [ronilaukkarinen/weed#42]
`trackbar22` in the README should just be `trackbar`. Just tried today and was curious why `trackbar22` wasn't working. Not sure why that's there.

**Comment by zoraj** [comment]
another typo: instead of /script load awl
it's /script load adv_windowlist

**Comment by ronilaukkarinen** [comment]
That's not actually a typo, it used to be awl. Same thing in trackbar, script has been updated but readme not. Will fix in some point... PRs welcome...
