### ISSUE TITLE
color picker

### ISSUE THREAD

**Issue by sbh7600** [ronilaukkarinen/weed#44]
Hello!

i don't get this : https://camo.githubusercontent.com/1e004b76aec0d6f2b21fef7245fce44ac823c7bb87546babb5a59955cc09175d/68747470733a2f2f692e696d6775722e636f6d2f366b7a366a49512e706e67

when following your install guide?

im on debian with mobaxterm?

**Comment by ronilaukkarinen** [comment]
Old tutorial, old screenshot. It's just optional way to set up colors. I don't know anything about mobaxterm.
