### ISSUE TITLE
How to get statusbar in README screenshot

### ISSUE THREAD

**Issue by mizlan** [ronilaukkarinen/weed#45]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/44309097/128615595-f88f03d0-c5e5-4f89-b4c5-a624d4c4f0bf.png">

In the image above, which code is responsible for making the row of neatly separated numbers and the channel name (`#pulina`)

I understand the leftmost user count number is `usercount.pl` but where is the rest? Using weed theme itself doesn't seem to provide this bar.

**Comment by ronilaukkarinen** [comment]
It's provided by [adv_windowlist.pl](https://github.com/ronilaukkarinen/weed/blob/master/scripts/adv_windowlist.pl).

The bottom bar is provided by tmux.
