### ISSUE TITLE
Add option to show channel names instead of numbers

### ISSUE THREAD

**Issue by mavam** [ronilaukkarinen/weed#5]
Thanks for making this neat theme available. I would like to show the channel names instead of numbers, because I don't want to cycle through all windows just to find the one I'm looking for. Is there an option that switches from numeric style to one that shows the channel names instead?

**Comment by ronilaukkarinen** [comment]
Yeah, that's more of the [advanced window list script](http://anti.teamidiot.de/static/nei/*/Code/Irssi/adv_windowlist.pl)'s stuff, but you can tweak with `/set awl_`, for example `/set awl_display_key %K%0$H $C %N`.

**Comment by mavam** [comment]
That worked for me, thanks.
