### ISSUE TITLE
Solarized Weed 

### ISSUE THREAD

**Issue by her** [ronilaukkarinen/weed#6]
Hey Roni & irssi weed community, love the theme, it *is* the most beautiful one in the world. However I'm running into to some configuration issues.

Here's the theme currently: 

![screen shot 2015-08-01 at 12 27 09 pm](https://cloud.githubusercontent.com/assets/10278096/9022576/c8d3126c-3848-11e5-9d37-b1747b032ca4.png)

But you can see I'm missing a few elements as they blend with my background Solarized color. Notably the name breaks ( | ), timestamps, and channelserv. This is observable by highlighting the window:

![screen shot 2015-08-01 at 12 27 47 pm](https://cloud.githubusercontent.com/assets/10278096/9022580/ed335bc6-3848-11e5-9806-ab597f91da0b.png)

Following the advice on your [blog](http://problemsolv.in/how-to-make-irssi-look-beautiful/) Roni, adjusting terminal colors also fails to correct this issue as it unfortunately breaks other things, like vim, and shell colors. :( 

I've tried modifying weed.theme which only resulted in me breaking everything, and having to restore from backup. 

Any advice here? How can I go about editing the weed.theme for my solarized colors? I don't know any perl, but maybe if I can get pointed in the right direction, I can start slowly modifying the weed.theme to accommodate for solarized users, and maybe help contribute to a weed.theme in solarized. 

Thoughts? 

Thanks everyone 

OS X 10.10.13 iTerm2

**Comment by ronilaukkarinen** [comment]
Hi Melanie, many thanks for the contribution! I'm glad you like my theme.
I'm fond of Monokai myself,  but Solarized looks so great I am willing to
create a Solarized specific weed theme. I'll bundle it within this repo
soon. It may help I'm also mainly a Mac user myself.

I'm currently in between of moving apartments (got my stuff in just now) so
it may take a while to get coding again, but please hang in there.

**Comment by yukie-** [comment]
Roni, thank you so much for the fast reply! A Solarized specific weed theme sounds *amazing* and I will most certainly hang in there.  I *just* finished moving between apartments too, so I know all about getting back into the swing of things while your stuff is scattered everywhere in boxes–haha. 

Don't hurt your back, and if there's anything you need help with let me know :)

**Comment by yukie-** [comment]
Roni,

This may be of some help as well https://github.com/huyz/irssi-colors-solarized so I'm going to leave it here :)

**Comment by wei2912** [comment]
I second this suggestion. :)

**Comment by ronilaukkarinen** [comment]
Ok I got tmux and [tmux-powerline](https://github.com/her/tmux-powerline) by @her and most of the outdated scripts up to date. @her, Could you please share the next steps how to make the setup 'Solarized' like yours. If possible, I'd use similar configuration to yours as possible.

**Comment by her** [comment]
Definitely sure! I'll try and include a couple extra details in case you wanna copy pasta to the About sections. 

* You need patched power line fonts for the glyphs in tmux-powerline to work. Simply clone from the  powerline/fonts repo https://github.com/powerline/fonts 

* Then use your preferred font manager to select and add your patched font to an already existing family or create a new one. 

<img width="1060" alt="screen shot 2015-09-07 at 9 56 17 am" src="https://cloud.githubusercontent.com/assets/10278096/9718106/d5412a3c-5546-11e5-9425-d79fe96109bc.png">


* Then select your new font as your terminal(CLI) font. 
<img width="966" alt="screen shot 2015-09-07 at 9 43 13 am" src="https://cloud.githubusercontent.com/assets/10278096/9718055/54679c52-5546-11e5-8177-cfa49ab7770a.png">

* Next get Solarized. This repo has all of the Solarized colors except vim(it has it's own repo). https://github.com/altercation/solarized -- Once you've cloned the solarized repo use the color theme for your respective CLI or terminal application, load and select the solarized theme you'd like(Dark of Light)

<img width="957" alt="screen shot 2015-09-07 at 9 41 51 am" src="https://cloud.githubusercontent.com/assets/10278096/9718124/edacfab0-5546-11e5-81e3-10576da6a771.png">

Done! Now you should have Solarized and a fancy Patched Powerline Font for your tmux/irssi setup.

**Comment by ronilaukkarinen** [comment]
Hello! I'm currently overworked with my dayjob, so I don't see this going forward... unfortunately. Feel free to continue this if you still want it. I'm currently using [Dracula theme](http://zenorocha.github.io/dracula-theme/) and never got used to Solarized. Also, it seems something is wrong with my Solarized setup, because I see all the theme colors properly:

![Screenshot](http://i.imgur.com/qcskJw8.png)

Anyway, I currently have no time for this. Sorry!

**Comment by her** [comment]
hey Roni thanks for making the attempt, hope work doesn't go too hard on you. Ill let you know if I make any progress on this! Best to you :)

**Comment by her** [comment]
hey Roni 

I completed the solarized theme of weed🌸 going to send you a PR, please let me know if you'd like me to change any of my additions.

I'm really happy with the theme and I'm excited that this issue can be closed! Hope you're doing well 👋🏻

![solarizedweedmac](https://cloud.githubusercontent.com/assets/10278096/15241456/e020f5c8-18a4-11e6-9fb0-76d7a6f9659c.png)

**Comment by ronilaukkarinen** [comment]
Hello @her! Looks awesome! I'm glad you did it, because I have been super busy and never got into Solarized (as I said before exactly in these words, I see, haha). Please do send a PR, happy to add it. :) thanks a lot!

**Comment by ronilaukkarinen** [comment]
[This](https://github.com/ronilaukkarinen/weed/pull/19) is now merged, so I'm closing the issue. Thanks again @her!
