### ISSUE TITLE
Make Username Tab more bigger

### ISSUE THREAD

**Issue by DeadalusHD** [ronilaukkarinen/weed#8]
https://i.imgur.com/EyczuLG.png

What field I need to change to accept more chars before the | comes?
Thanks

**Comment by ronilaukkarinen** [comment]
`own_msg`, `pubmsg` and variants. Search for `[-10]` and change that amount (it's 10 chars by default). You will also need to edit `nickcolor.pl` accordingly.

**Comment by DeadalusHD** [comment]
Thanks, exaclty what I was looking for.

**Comment by DeadalusHD** [comment]
Made the changes, everything worked as expected, thanks!

**Comment by ronilaukkarinen** [comment]
You're welcome! Thanks for using my theme.

**Comment by DeadalusHD** [comment]
I changed everything but for some reason the server messages are not the same as the own / user messages.

https://i.imgur.com/VGnkWys.png

Did I forgot something to change?
Changed every value from -10 to -14 and also reloaded and restarted irssi

**Comment by ronilaukkarinen** [comment]
Oh yes, you need to add that many spaces (4) to every line with `|`, just before the character.

Changing character limit on the fly is not implemented as a setting (or even possible without a script) and back when I designed the theme I noticed over 10 characters for nick is taking too much space on mobile screens so that's why 10 is default.

**Comment by Aebian** [comment]
Allright, I will do that then ;D

**Comment by Aebian** [comment]
Thanks Roni but now I got a %% on every text I'm writing.
 13:10          Aebian    | %%    |wat

Did I messed up somewhere? Tried to search for "%%" but nothing usefull was found :D

**Comment by Aebian** [comment]
I fixed it now. thanks for your theme and the help.
Have a nice day!
